name: 'main'

on:
  push:
  pull_request:

jobs:


  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        TEST_CASE:
          - tests/onenet
          - tests/OneNetModport
          - tests/OneFF
          - tests/OneAnd
          - tests/OneDivider
          - tests/OneNetInterf
          - tests/OneNetRange
          - tests/OneConcat
          - tests/OneReplicate
          - tests/OneAlwaysComb
          - tests/OneShift
          - tests/OneArithShift
          - tests/OneSysFunc
          - tests/OneInside
          - tests/OneImport
          - tests/OneCast
          - tests/OnePackage
          - tests/OneStruct
          - tests/fsm_single_always
          - tests/fsm_using_function
          - tests/fsm_using_always
          - tests/AluOps
          - tests/UnitForLoop
          - tests/GenerateAssigns
          - tests/AssignmentPattern
          - tests/MultipleCells
          - tests/IndexedPartSelect
          - tests/PartSelect
          - tests/VarSelect
          - tests/EnumInPackage
          - tests/StructInPackage
        TARGET:
          - uhdm/yosys/test-ast
          - uhdm/verilator/test-ast
        exclude:
          - TEST_CASE: tests/EnumInPackage
            TARGET: uhdm/verilator/test-ast
          - TEST_CASE: tests/StructInPackage
            TARGET: uhdm/verilator/test-ast
          - TEST_CASE: tests/OneThis
            TARGET: uhdm/verilator/test-ast
      fail-fast:
        false
    env:
      CC: gcc-9
      CXX: g++-9

    steps:

    - name: Install dependencies
      run: |
        sudo apt-get update -qq
        sudo apt install -y g++-9 build-essential cmake tclsh ant default-jre swig google-perftools libgoogle-perftools-dev python3 python3-dev uuid uuid-dev tcl-dev flex libfl-dev

    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0

    - uses: actions/setup-python@v2
      with:
         python-version: '3.x'

    - name: Build & Test
      run: ./.github/travis/script.sh
      env:
        TEST_CASE: ${{ matrix.TEST_CASE }}
        TARGET: ${{ matrix.TARGET }}


  surelog-uhdm:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      CC: gcc-9
      CXX: g++-9

    steps:

    - name: Install dependencies
      run: |
        sudo apt-get update -qq
        sudo apt install -y g++-9 build-essential cmake tclsh ant default-jre swig google-perftools libgoogle-perftools-dev python3 python3-dev uuid uuid-dev tcl-dev flex libfl-dev

    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0

    - uses: actions/setup-python@v2
      with:
         python-version: '3.x'

    - name: Build & Test
      run: ./.github/travis/script.sh
      env:
        MODE: surelog-uhdm


  ibex_synth:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        TARGET: [uhdm/yosys/synth-ibex]
      fail-fast:
        false
    env:
      CC: gcc-9
      CXX: g++-9

    steps:

    - name: Install dependencies
      run: |
        sudo apt-get update -qq
        sudo apt install -y g++-9 build-essential cmake tclsh ant default-jre swig google-perftools libgoogle-perftools-dev python3 python3-dev uuid uuid-dev tcl-dev flex libfl-dev

    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 0

    - uses: actions/setup-python@v2
      with:
         python-version: '3.7'

    - name: Build & Test
      run: |
        pip install virtualenv
        virtualenv venv-ibex
        . venv-ibex/bin/activate
        pip install -r tests/ibex/ibex/python-requirements.txt
        cd tests/ibex/ibex
        fusesoc --cores-root=. run --target=synth --setup lowrisc:ibex:top_artya7 --part xc7a35ticsg324-1L
        cd ../../..
        ./.github/travis/script.sh
      env:
        TARGET: uhdm/yosys/synth-ibex
        TEST_CASE: tests/ibex
